name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^3.0.0-dev.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: any
  font_awesome_flutter: ^10.7.0
  glowy_borders: any
  google_fonts: ^6.2.1
  http: ^1.2.2
  lottie: ^3.1.2
  model_viewer_plus: any
  rive: ^0.13.13
  riverpod_annotation: ^3.0.0-dev.3
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  supabase_flutter: ^2.6.0
  syncfusion_flutter_charts: any
  fpdart: any
  gotrue: any
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.0
dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0
  flutter_test:
    sdk: flutter
  

flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth_icons/
    - assets/images/backgrounds/
    - assets/images/planet_icons/
    - assets/videos/
    - assets/animations/
    - assets/animations/exoplanets/
