name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  animate_do: ^3.3.4
  animated_text_kit: ^4.2.2
  cupertino_icons: ^1.0.6
  dots_indicator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: any
  font_awesome_flutter: ^10.7.0
  glowy_borders: any
  google_fonts: ^6.2.1
  http: ^1.2.2
  lottie: ^3.1.2
  model_viewer_plus: any
  rive: ^0.13.13
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  supabase_flutter: ^2.6.0
  syncfusion_flutter_charts: any
  fpdart: any
  gotrue: any
  internet_connection_checker_plus: ^2.5.2
  get_it: ^8.0.0
  flutter_test:
    sdk: flutter
dev_dependencies:
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
build_runner:
  riverpod_generator: ^2.4.3
  riverpod_lint: ^2.3.13
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  http: ^0.13.4


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/auth_icons/
    - assets/images/backgrounds/
    - assets/images/planet_icons/
    - assets/videos/
    - assets/animations/
    - assets/animations/exoplanets/
