export 'onboarding/welcome_screen.dart';
// SIGNUP
export 'auth/screens/signup/add_your_email.dart';
export 'auth/screens/signup/create_new_account.dart';
export 'auth/screens/signup/create_your_password.dart';
export 'auth/screens/signup/signup_controller.dart';
export 'auth/screens/signup/verify_email.dart';
export 'auth/screens/signup/succesful_account_creation.dart';
export 'auth/screens/forgotpassword/forgot_password.dart';
export 'auth/screens/forgotpassword/forgot_password_controller.dart';
export 'auth/screens/login/login_screen.dart';
// HOME
export 'home/screens/home_view.dart';
// AUTH
// EXOPLANETS
export 'home/screens/exoplanet/screens/exoplanet_details.dart';
export 'home/screens/exoplanet/screens/space_ship_view.dart';
