class Failure {
  final String message;
  Failure(this.message);
  static const String invalidEmail = 'Invalid email';
  static const String invalidPassword = 'Invalid password';
  static const String invalidName = 'Invalid name';
  static const String invalidPhoneNumber = 'Invalid phone number';
  static const String invalidAddress = 'Invalid address';
  static const String invalidCity = 'Invalid city';
  static const String invalidState = 'Invalid state';
  static const String invalidZipCode = 'Invalid zip code';
  static const String invalidCountry = 'Invalid country';
  static const String invalidCardNumber = 'Invalid card number';
  static const String invalidCardHolder = 'Invalid card holder';
  static const String invalidCardExpDate = 'Invalid card expiration date';
  static const String invalidCardCvv = 'Invalid card CVV';
  static const String invalidCardType = 'Invalid card type';
  static const String invalidCardBrand = 'Invalid card brand';
  static const String invalidCardLast4 = 'Invalid card last 4 digits';
  static const String invalidCardExpMonth = 'Invalid card expiration month';
  static const String invalidCardExpYear = 'Invalid card expiration year';
  static const String invalidCardExp = 'Invalid card expiration';
  static const String invalidCard = 'Invalid card';
  static const String invalidCardToken = 'Invalid card token';
  static const String invalidCardId = 'Invalid card id';
  static const String invalidCardFingerprint = 'Invalid card fingerprint';
  static const String invalidCardCountry = 'Invalid card country';
  static const String invalidCardCurrency = 'Invalid card currency';
  static const String invalidCardFunding = 'Invalid card funding';
  static const String invalidCardBank = 'Invalid card bank';
  static const String invalidCardAddress = 'Invalid card address';
  static const String invalidCardZipCode = 'Invalid card zip code';
  static const String invalidCardCity = 'Invalid card city';
  static const String invalidCardState = 'Invalid card state';
  static const String invalidCardCountryCode = 'Invalid card country code';
  static const String invalidCardCountryName = 'Invalid card country name';
  static const String invalidCardCountryAlpha2 = 'Invalid card country alpha 2';
  static const String invalidCardCountryAlpha3 = 'Invalid card country alpha 3';
  static const String invalidCardCountryNumeric =
      'Invalid card country numeric';
  static const String invalidCardCountryEmoji = 'Invalid card country emoji';
}
